name: Package with Maven

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-redis-pageview
          path: target/*.jar
